version: '3.8'

services:
  angular-dev:
    container_name: angular-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      #- /app/node_modules
    stdin_open: true
    tty: true
