// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory/index.ts to modify the generation of this file.
// Use app-components.shared.module.ts to modify the imports, etc of this module.
// Note: code-generation is optional! See ./.gitignore for directions to remove it,
// if you do not want it.

import { CUSTOM_ELEMENTS_SCHEMA,NgModule } from '@angular/core';
import { JssModule } from '@sitecore-jss/sitecore-jss-angular';
import { AppComponentsSharedModule } from './app-components.shared.module';
import { LocalizedDatePipe } from '../Pipes/localized-date.pipe';
import { NgbPaginationModule } from '@ng-bootstrap/ng-bootstrap';
import { PaginationModule } from 'ngx-bootstrap/pagination';
import { LightboxModule } from 'ngx-lightbox';
import { CarouselModule } from 'ngx-owl-carousel-o';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgxExtendedPdfViewerModule } from 'ngx-extended-pdf-viewer';
import { GlobalService } from '../services/global.service';
import { SafeUrlPipe } from '../Pipes/safe-url.pipe';
import { SlickCarouselModule } from 'ngx-slick-carousel';
import { OrganizationChartModule } from 'primeng/organizationchart';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';

import { AboutMinisterComponent } from './about-minister/about-minister.component';
import { AboutMinistryComponent } from './about-ministry/about-ministry.component';
import { AllNewsListingComponent } from './all-news-listing/all-news-listing.component';
import { BreadcrumbComponent } from './breadcrumb/breadcrumb.component';
import { CategoryComponent } from './category/category.component';
import { CheckboxListComponent } from './checkbox-list/checkbox-list.component';
import { ConsortiumComponent } from './consortium/consortium.component';
import { ContactFormComponent } from './contact-form/contact-form.component';
import { ContactInformationComponent } from './contact-information/contact-information.component';
import { ContactUsComponent } from './contact-us/contact-us.component';
import { ContentBlockComponent } from './content-block/content-block.component';
import { EstablishmentComponent } from './establishment/establishment.component';
import { FactsandFigureComponent } from './factsand-figure/factsand-figure.component';
import { FallbackRenderingComponent } from './fallback-rendering/fallback-rendering.component';
import { FaqComponent } from './faq/faq.component';
import { FooterComponent } from './footer/footer.component';
import { GraphQLConnectedDemoComponent } from './graph-ql-connected-demo/graph-ql-connected-demo.component';
import { GraphQLIntegratedDemoComponent } from './graph-ql-integrated-demo/graph-ql-integrated-demo.component';
import { GraphQLLayoutComponent } from './graph-ql-layout/graph-ql-layout.component';
import { HeaderComponent } from './header/header.component';
import { HeroComponent } from './hero/hero.component';
import { ImageGalleryComponent } from './image-gallery/image-gallery.component';
import { InfographicsComponent } from './infographics/infographics.component';
import { InfographicsGridComponent } from './infographics-grid/infographics-grid.component';
import { InitativeAwardComponent } from './initative-award/initative-award.component';
import { InitativeContactInfoComponent } from './initative-contact-info/initative-contact-info.component';
import { InitativeGoalComponent } from './initative-goal/initative-goal.component';
import { InitativeImageWithDescriptionComponent } from './initative-image-with-description/initative-image-with-description.component';
import { InitativeTrainingProcessComponent } from './initative-training-process/initative-training-process.component';
import { InitiativeFactsComponent } from './initiative-facts/initiative-facts.component';
import { InitiativesComponent } from './initiatives/initiatives.component';
import { InitiativesGridComponent } from './initiatives-grid/initiatives-grid.component';
import { JobDetailComponent } from './job-detail/job-detail.component';
import { JobFormComponent } from './job-form/job-form.component';
import { JobsListingComponent } from './jobs-listing/jobs-listing.component';
import { LatestnewsComponent } from './latestnews/latestnews.component';
import { MediaHubComponent } from './media-hub/media-hub.component';
import { MediaLeadersComponent } from './media-leaders/media-leaders.component';
import { MediaServiceDetailComponent } from './media-service-detail/media-service-detail.component';
import { MediaServiceListingComponent } from './media-service-listing/media-service-listing.component';
import { MediaSystemComponent } from './media-system/media-system.component';
import { MinisterMessageComponent } from './minister-message/minister-message.component';
import { MinistryLeaderDetailComponent } from './ministry-leader-detail/ministry-leader-detail.component';
import { MinistryMediaComponent } from './ministry-media/ministry-media.component';
import { NewBreadCrumbComponent } from './new-bread-crumb/new-bread-crumb.component';
import { NewsComponent } from './news/news.component';
import { NewsDetailComponent } from './news-detail/news-detail.component';
import { NewsListingComponent } from './news-listing/news-listing.component';
import { OrganizationalChartComponent } from './organizational-chart/organizational-chart.component';
import { PageRatingComponent } from './page-rating/page-rating.component';
import { RatingsFormComponent } from './ratings-form/ratings-form.component';
import { ReadingInfoComponent } from './reading-info/reading-info.component';
import { RegulationsSystemComponent } from './regulations-system/regulations-system.component';
import { ReportDetailComponent } from './report-detail/report-detail.component';
import { ReportListingComponent } from './report-listing/report-listing.component';
import { RulesViewComponent } from './rules-view/rules-view.component';
import { SearchResultComponent } from './search-result/search-result.component';
import { SearchResultsComponent } from './search-results/search-results.component';
import { SharedTitleAndIconsComponent } from './shared-title-and-icons/shared-title-and-icons.component';
import { SiteMapComponent } from './site-map/site-map.component';
import { SitemapComponent } from './sitemap/sitemap.component';
import { SmallHeroComponent } from './small-hero/small-hero.component';
import { SocialMediaComponent } from './social-media/social-media.component';
import { StyleguideComponentParamsComponent } from './styleguide-component-params/styleguide-component-params.component';
import { StyleguideCustomRouteTypeComponent } from './styleguide-custom-route-type/styleguide-custom-route-type.component';
import { StyleguideEditFrameComponent } from './styleguide-edit-frame/styleguide-edit-frame.component';
import { StyleguideFieldUsageCheckboxComponent } from './styleguide-field-usage-checkbox/styleguide-field-usage-checkbox.component';
import { StyleguideFieldUsageContentListComponent } from './styleguide-field-usage-content-list/styleguide-field-usage-content-list.component';
import { StyleguideFieldUsageCustomComponent } from './styleguide-field-usage-custom/styleguide-field-usage-custom.component';
import { StyleguideFieldUsageDateComponent } from './styleguide-field-usage-date/styleguide-field-usage-date.component';
import { StyleguideFieldUsageFileComponent } from './styleguide-field-usage-file/styleguide-field-usage-file.component';
import { StyleguideFieldUsageImageComponent } from './styleguide-field-usage-image/styleguide-field-usage-image.component';
import { StyleguideFieldUsageItemLinkComponent } from './styleguide-field-usage-item-link/styleguide-field-usage-item-link.component';
import { StyleguideFieldUsageLinkComponent } from './styleguide-field-usage-link/styleguide-field-usage-link.component';
import { StyleguideFieldUsageNumberComponent } from './styleguide-field-usage-number/styleguide-field-usage-number.component';
import { StyleguideFieldUsageRichTextComponent } from './styleguide-field-usage-rich-text/styleguide-field-usage-rich-text.component';
import { StyleguideFieldUsageTextComponent } from './styleguide-field-usage-text/styleguide-field-usage-text.component';
import { StyleguideLayoutComponent } from './styleguide-layout/styleguide-layout.component';
import { StyleguideLayoutReuseComponent } from './styleguide-layout-reuse/styleguide-layout-reuse.component';
import { StyleguideLayoutTabsComponent } from './styleguide-layout-tabs/styleguide-layout-tabs.component';
import { StyleguideLayoutTabsTabComponent } from './styleguide-layout-tabs-tab/styleguide-layout-tabs-tab.component';
import { StyleguideMultilingualComponent } from './styleguide-multilingual/styleguide-multilingual.component';
import { StyleguideRouteFieldsComponent } from './styleguide-route-fields/styleguide-route-fields.component';
import { StyleguideSectionComponent } from './styleguide-section/styleguide-section.component';
import { StyleguideSitecoreContextComponent } from './styleguide-sitecore-context/styleguide-sitecore-context.component';
import { StyleguideTrackingComponent } from './styleguide-tracking/styleguide-tracking.component';
import { SummitsComponent } from './summits/summits.component';
import { UnderDevelopmentComponent } from './under-development/under-development.component';
import { VideoGalleryComponent } from './video-gallery/video-gallery.component';
import { VisionMissionComponent } from './vision-mission/vision-mission.component';

export const components = [
  'AboutMinister',
  'AboutMinistry',
  'AllNewsListing',
  'Breadcrumb',
  'Category',
  'CheckboxList',
  'Consortium',
  'ContactForm',
  'ContactInformation',
  'ContactUs',
  'ContentBlock',
  'Establishment',
  'FactsandFigure',
  'FallbackRendering',
  'Faq',
  'Footer',
  'GraphQLConnectedDemo',
  'GraphQLIntegratedDemo',
  'GraphQLLayout',
  'Header',
  'Hero',
  'ImageGallery',
  'Infographics',
  'InfographicsGrid',
  'InitativeAward',
  'InitativeContactInfo',
  'InitativeGoal',
  'InitativeImageWithDescription',
  'InitativeTrainingProcess',
  'InitiativeFacts',
  'Initiatives',
  'InitiativesGrid',
  'JobDetail',
  'JobForm',
  'JobsListing',
  'Latestnews',
  'MediaHub',
  'MediaLeaders',
  'MediaServiceDetail',
  'MediaServiceListing',
  'MediaSystem',
  'MinisterMessage',
  'MinistryLeaderDetail',
  'MinistryMedia',
  'NewBreadCrumb',
  'News',
  'NewsDetail',
  'NewsListing',
  'OrganizationalChart',
  'PageRating',
  'RatingsForm',
  'ReadingInfo',
  'RegulationsSystem',
  'ReportDetail',
  'ReportListing',
  'RulesView',
  'SearchResult',
  'SearchResults',
  'SharedTitleAndIcons',
  'SiteMap',
  'Sitemap',
  'SmallHero',
  'SocialMedia',
  'StyleguideAngularLazyLoading',
  'StyleguideComponentParams',
  'StyleguideCustomRouteType',
  'StyleguideEditFrame',
  'StyleguideFieldUsageCheckbox',
  'StyleguideFieldUsageContentList',
  'StyleguideFieldUsageCustom',
  'StyleguideFieldUsageDate',
  'StyleguideFieldUsageFile',
  'StyleguideFieldUsageImage',
  'StyleguideFieldUsageItemLink',
  'StyleguideFieldUsageLink',
  'StyleguideFieldUsageNumber',
  'StyleguideFieldUsageRichText',
  'StyleguideFieldUsageText',
  'StyleguideLayout',
  'StyleguideLayoutReuse',
  'StyleguideLayoutTabs',
  'StyleguideLayoutTabsTab',
  'StyleguideMultilingual',
  'StyleguideRouteFields',
  'StyleguideSection',
  'StyleguideSitecoreContext',
  'StyleguideTracking',
  'Summits',
  'UnderDevelopment',
  'VideoGallery',
  'VisionMission'
];

@NgModule({
  imports: [
    PaginationModule.forRoot(),
    NgbPaginationModule,
    AppComponentsSharedModule,
    LightboxModule,
    CarouselModule,
    FormsModule,
    ReactiveFormsModule,
    NgxExtendedPdfViewerModule,
    OrganizationChartModule,
    SlickCarouselModule,
    JssModule.withComponents([
      { name: 'AboutMinister', type: AboutMinisterComponent },
      { name: 'AboutMinistry', type: AboutMinistryComponent },
      { name: 'AllNewsListing', type: AllNewsListingComponent },
      { name: 'Breadcrumb', type: BreadcrumbComponent },
      { name: 'Category', type: CategoryComponent },
      { name: 'CheckboxList', type: CheckboxListComponent },
      { name: 'Consortium', type: ConsortiumComponent },
      { name: 'ContactForm', type: ContactFormComponent },
      { name: 'ContactInformation', type: ContactInformationComponent },
      { name: 'ContactUs', type: ContactUsComponent },
      { name: 'ContentBlock', type: ContentBlockComponent },
      { name: 'Establishment', type: EstablishmentComponent },
      { name: 'FactsandFigure', type: FactsandFigureComponent },
      { name: 'FallbackRendering', type: FallbackRenderingComponent },
      { name: 'Faq', type: FaqComponent },
      { name: 'Footer', type: FooterComponent },
      { name: 'GraphQLConnectedDemo', type: GraphQLConnectedDemoComponent },
      { name: 'GraphQLIntegratedDemo', type: GraphQLIntegratedDemoComponent },
      { name: 'GraphQLLayout', type: GraphQLLayoutComponent },
      { name: 'Header', type: HeaderComponent },
      { name: 'Hero', type: HeroComponent },
      { name: 'ImageGallery', type: ImageGalleryComponent },
      { name: 'Infographics', type: InfographicsComponent },
      { name: 'InfographicsGrid', type: InfographicsGridComponent },
      { name: 'InitativeAward', type: InitativeAwardComponent },
      { name: 'InitativeContactInfo', type: InitativeContactInfoComponent },
      { name: 'InitativeGoal', type: InitativeGoalComponent },
      { name: 'InitativeImageWithDescription', type: InitativeImageWithDescriptionComponent },
      { name: 'InitativeTrainingProcess', type: InitativeTrainingProcessComponent },
      { name: 'InitiativeFacts', type: InitiativeFactsComponent },
      { name: 'Initiatives', type: InitiativesComponent },
      { name: 'InitiativesGrid', type: InitiativesGridComponent },
      { name: 'JobDetail', type: JobDetailComponent },
      { name: 'JobForm', type: JobFormComponent },
      { name: 'JobsListing', type: JobsListingComponent },
      { name: 'Latestnews', type: LatestnewsComponent },
      { name: 'MediaHub', type: MediaHubComponent },
      { name: 'MediaLeaders', type: MediaLeadersComponent },
      { name: 'MediaServiceDetail', type: MediaServiceDetailComponent },
      { name: 'MediaServiceListing', type: MediaServiceListingComponent },
      { name: 'MediaSystem', type: MediaSystemComponent },
      { name: 'MinisterMessage', type: MinisterMessageComponent },
      { name: 'MinistryLeaderDetail', type: MinistryLeaderDetailComponent },
      { name: 'MinistryMedia', type: MinistryMediaComponent },
      { name: 'NewBreadCrumb', type: NewBreadCrumbComponent },
      { name: 'News', type: NewsComponent },
      { name: 'NewsDetail', type: NewsDetailComponent },
      { name: 'NewsListing', type: NewsListingComponent },
      { name: 'OrganizationalChart', type: OrganizationalChartComponent },
      { name: 'PageRating', type: PageRatingComponent },
      { name: 'RatingsForm', type: RatingsFormComponent },
      { name: 'ReadingInfo', type: ReadingInfoComponent },
      { name: 'RegulationsSystem', type: RegulationsSystemComponent },
      { name: 'ReportDetail', type: ReportDetailComponent },
      { name: 'ReportListing', type: ReportListingComponent },
      { name: 'RulesView', type: RulesViewComponent },
      { name: 'SearchResult', type: SearchResultComponent },
      { name: 'SearchResults', type: SearchResultsComponent },
      { name: 'SharedTitleAndIcons', type: SharedTitleAndIconsComponent },
      { name: 'SiteMap', type: SiteMapComponent },
      { name: 'Sitemap', type: SitemapComponent },
      { name: 'SmallHero', type: SmallHeroComponent },
      { name: 'SocialMedia', type: SocialMediaComponent },
      { name: 'StyleguideComponentParams', type: StyleguideComponentParamsComponent },
      { name: 'StyleguideCustomRouteType', type: StyleguideCustomRouteTypeComponent },
      { name: 'StyleguideEditFrame', type: StyleguideEditFrameComponent },
      { name: 'StyleguideFieldUsageCheckbox', type: StyleguideFieldUsageCheckboxComponent },
      { name: 'StyleguideFieldUsageContentList', type: StyleguideFieldUsageContentListComponent },
      { name: 'StyleguideFieldUsageCustom', type: StyleguideFieldUsageCustomComponent },
      { name: 'StyleguideFieldUsageDate', type: StyleguideFieldUsageDateComponent },
      { name: 'StyleguideFieldUsageFile', type: StyleguideFieldUsageFileComponent },
      { name: 'StyleguideFieldUsageImage', type: StyleguideFieldUsageImageComponent },
      { name: 'StyleguideFieldUsageItemLink', type: StyleguideFieldUsageItemLinkComponent },
      { name: 'StyleguideFieldUsageLink', type: StyleguideFieldUsageLinkComponent },
      { name: 'StyleguideFieldUsageNumber', type: StyleguideFieldUsageNumberComponent },
      { name: 'StyleguideFieldUsageRichText', type: StyleguideFieldUsageRichTextComponent },
      { name: 'StyleguideFieldUsageText', type: StyleguideFieldUsageTextComponent },
      { name: 'StyleguideLayout', type: StyleguideLayoutComponent },
      { name: 'StyleguideLayoutReuse', type: StyleguideLayoutReuseComponent },
      { name: 'StyleguideLayoutTabs', type: StyleguideLayoutTabsComponent },
      { name: 'StyleguideLayoutTabsTab', type: StyleguideLayoutTabsTabComponent },
      { name: 'StyleguideMultilingual', type: StyleguideMultilingualComponent },
      { name: 'StyleguideRouteFields', type: StyleguideRouteFieldsComponent },
      { name: 'StyleguideSection', type: StyleguideSectionComponent },
      { name: 'StyleguideSitecoreContext', type: StyleguideSitecoreContextComponent },
      { name: 'StyleguideTracking', type: StyleguideTrackingComponent },
      { name: 'Summits', type: SummitsComponent },
      { name: 'UnderDevelopment', type: UnderDevelopmentComponent },
      { name: 'VideoGallery', type: VideoGalleryComponent },
      { name: 'VisionMission', type: VisionMissionComponent },
    ], [
      { path: 'StyleguideAngularLazyLoading', loadChildren: () => import('./styleguide-angular-lazy-loading/styleguide-angular-lazy-loading.module').then(m => m.StyleguideAngularLazyLoadingModule) },
    
    ]),
  ],
  exports: [
    JssModule,
    AppComponentsSharedModule,
    NewsListingComponent,
    NgbPaginationModule,
    PaginationModule
  ],
  declarations: [
    AboutMinisterComponent,
    AboutMinistryComponent,
    AllNewsListingComponent,
    BreadcrumbComponent,
    CategoryComponent,
    CheckboxListComponent,
    ConsortiumComponent,
    ContactFormComponent,
    ContactInformationComponent,
    ContactUsComponent,
    ContentBlockComponent,
    EstablishmentComponent,
    FactsandFigureComponent,
    FallbackRenderingComponent,
    FaqComponent,
    FooterComponent,
    GraphQLConnectedDemoComponent,
    GraphQLIntegratedDemoComponent,
    GraphQLLayoutComponent,
    HeaderComponent,
    HeroComponent,
    ImageGalleryComponent,
    InfographicsComponent,
    InfographicsGridComponent,
    InitativeAwardComponent,
    InitativeContactInfoComponent,
    InitativeGoalComponent,
    InitativeImageWithDescriptionComponent,
    InitativeTrainingProcessComponent,
    InitiativeFactsComponent,
    InitiativesComponent,
    InitiativesGridComponent,
    JobDetailComponent,
    JobFormComponent,
    JobsListingComponent,
    LatestnewsComponent,
    MediaHubComponent,
    MediaLeadersComponent,
    MediaServiceDetailComponent,
    MediaServiceListingComponent,
    MediaSystemComponent,
    MinisterMessageComponent,
    MinistryLeaderDetailComponent,
    MinistryMediaComponent,
    NewBreadCrumbComponent,
    NewsComponent,
    NewsDetailComponent,
    NewsListingComponent,
    OrganizationalChartComponent,
    PageRatingComponent,
    RatingsFormComponent,
    ReadingInfoComponent,
    RegulationsSystemComponent,
    ReportDetailComponent,
    ReportListingComponent,
    RulesViewComponent,
    SearchResultComponent,
    SearchResultsComponent,
    SharedTitleAndIconsComponent,
    SiteMapComponent,
    SitemapComponent,
    SmallHeroComponent,
    SocialMediaComponent,
    StyleguideComponentParamsComponent,
    StyleguideCustomRouteTypeComponent,
    StyleguideEditFrameComponent,
    StyleguideFieldUsageCheckboxComponent,
    StyleguideFieldUsageContentListComponent,
    StyleguideFieldUsageCustomComponent,
    StyleguideFieldUsageDateComponent,
    StyleguideFieldUsageFileComponent,
    StyleguideFieldUsageImageComponent,
    StyleguideFieldUsageItemLinkComponent,
    StyleguideFieldUsageLinkComponent,
    StyleguideFieldUsageNumberComponent,
    StyleguideFieldUsageRichTextComponent,
    StyleguideFieldUsageTextComponent,
    StyleguideLayoutComponent,
    StyleguideLayoutReuseComponent,
    StyleguideLayoutTabsComponent,
    StyleguideLayoutTabsTabComponent,
    StyleguideMultilingualComponent,
    StyleguideRouteFieldsComponent,
    StyleguideSectionComponent,
    StyleguideSitecoreContextComponent,
    StyleguideTrackingComponent,
    SummitsComponent,
    UnderDevelopmentComponent,
    VideoGalleryComponent,
    VisionMissionComponent,
    SafeUrlPipe,
    LocalizedDatePipe,

   ],
     providers: [
       GlobalService,
       provideAnimationsAsync(),
     ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppComponentsModule { }
