export const componentFactoryTemplate = ({
  imports,
  components,
  registrations,
  lazyRegistrations,
  declarations,
}: {
  imports: string[];
  components: string[];
  registrations: string[];
  lazyRegistrations: string[];
  declarations: string[];
}) => `// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory/index.ts to modify the generation of this file.
// Use app-components.shared.module.ts to modify the imports, etc of this module.
// Note: code-generation is optional! See ./.gitignore for directions to remove it,
// if you do not want it.

import { CUSTOM_ELEMENTS_SCHEMA,NgModule } from '@angular/core';
import { JssModule } from '@sitecore-jss/sitecore-jss-angular';
import { AppComponentsSharedModule } from './app-components.shared.module';
import { LocalizedDatePipe } from '../Pipes/localized-date.pipe';
import { NgbPaginationModule } from '@ng-bootstrap/ng-bootstrap';
import { PaginationModule } from 'ngx-bootstrap/pagination';
import { LightboxModule } from 'ngx-lightbox';
import { CarouselModule } from 'ngx-owl-carousel-o';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgxExtendedPdfViewerModule } from 'ngx-extended-pdf-viewer';
import { GlobalService } from '../services/global.service';
import { SafeUrlPipe } from '../Pipes/safe-url.pipe';
import { SlickCarouselModule } from 'ngx-slick-carousel';
import { OrganizationChartModule } from 'primeng/organizationchart';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';

${imports.join('\n')}

export const components = [
  ${components.map((c) => `'${c}'`).join(',\n  ')}
];

@NgModule({
  imports: [
    PaginationModule.forRoot(),
    NgbPaginationModule,
    AppComponentsSharedModule,
    LightboxModule,
    CarouselModule,
    FormsModule,
    ReactiveFormsModule,
    NgxExtendedPdfViewerModule,
    OrganizationChartModule,
    SlickCarouselModule,
    JssModule.withComponents([
      ${registrations.join('\n      ')}
    ], [
      ${lazyRegistrations.join('\n      ')}
    
    ]),
  ],
  exports: [
    JssModule,
    AppComponentsSharedModule,
    NewsListingComponent,
    NgbPaginationModule,
    PaginationModule
  ],
  declarations: [
    ${declarations.join('\n    ')}
    SafeUrlPipe,
    LocalizedDatePipe,

   ],
     providers: [
       GlobalService,
       provideAnimationsAsync(),
     ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppComponentsModule { }
`;
